- name: Ensure Docker network app-net exists
  hosts: all
  become: true
  tasks:
    - name: Create Docker network
      docker_network:
        name: app-net
        state: present

- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
